[language-server]
deno = { command = "deno", args = [ "lsp" ]}
emmet-ls = { command = "emmet-ls", args = [ "--stdio" ]}

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
feature_words = true
feature_snippets = true
snippets_first = true
snippets_inline_by_word_tail = false
feature_unicode_input = false
feature_paths = false

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true


[[language]]
name = "typescript"
language-servers = [ "scls", "typescript-language-server", "eslint", "tailwindcss-ls" ]
# formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "scls", "typescript-language-server", "eslint", "emmet-ls", "tailwindcss-ls" ]
# formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "scls", "typescript-language-server", "eslint", "tailwindcss-ls" ]
# formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
formatter = { command = "prettier", args = [ "--parser", "babel" ] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "scls", "typescript-language-server", "eslint", "emmet-ls", "tailwindcss-ls" ]
# formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
formatter = { command = "prettier", args = [ "--parser", "babel" ] }
auto-format = true

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
formatter = { command = "prettier", args = [ "--parser", "json" ] }
auto-format = true

# [[language]]
# name = "html"
# language-servers = [ "vscode-html-language-server", "emmet-ls", "tailwindcss-ls" ]
# formatter = { command = 'prettier', args = ["--parser", "html"] }
# auto-format = true

[[language]]
name = "html"
file-types = ["html"]
auto-format = true
language-servers = ["vscode-html-language-server", "harper-ls"]
formatter = { command = "prettier", args = ["--parser", "html"] }


[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "emmet-ls", "tailwindcss-ls" ]
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "c"
language-servers = [ "clangd" ]
auto-format = true

# [[language]]
# name = "markdown"
# language-server = { command = "/path/to/mdpls" }
# config = { markdown.preview.auto = true, markdown.preview.browser = "firefox" }

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = false

[[language]]
name = "python"
auto-format = true  # ":toggle-option autoformat" to disable
# Requires ruff, that can be installed with pipx
formatter = { command = "sh", args = ["-c", """
  ruff check --select I --fix - | ruff format -
  """] }
